steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-cloud-run-app', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-cloud-run-app']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'react-cloud-run-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/react-cloud-run-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'  # Replace with your region
      - '--allow-unauthenticated'

# Define the substitution for Cloud Build to use your project ID
substitutions:
  _SERVICE_NAME: "react-cloud-run-app"

timeout: 900s  # Optional: Extend timeout if build takes long
